---
name: Local pipeline

on: [push, pull_request]  # yamllint disable-line rule:truthy

permissions:
  contents: read

jobs:
  pathcheck:
    uses: ./.github/workflows/pathcheck.yml

  yamllint:
    uses: ./.github/workflows/yamllint.yml
